branch-defaults:
  master:
    environment: sterilog-dev
environment-defaults:
  Sterilog-env:
    branch: null
    repository: null
global:
  application_name: Sterilog
  default_ec2_keyname: aws-eb
  default_platform: PHP
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
